// <auto-generated />
using System;
using Armeccor.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Armeccor.Datos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260109212734_Propiedad")]
    partial class Propiedad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Armeccor.Datos.Entidades.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("NombreArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstaActivo = false,
                            NombreArea = "Mecanizado"
                        },
                        new
                        {
                            Id = 2,
                            EstaActivo = false,
                            NombreArea = "Soldadura"
                        },
                        new
                        {
                            Id = 3,
                            EstaActivo = false,
                            NombreArea = "Pintura"
                        },
                        new
                        {
                            Id = 4,
                            EstaActivo = false,
                            NombreArea = "Calidad"
                        },
                        new
                        {
                            Id = 5,
                            EstaActivo = false,
                            NombreArea = "Embalaje"
                        },
                        new
                        {
                            Id = 6,
                            EstaActivo = false,
                            NombreArea = "Logística"
                        },
                        new
                        {
                            Id = 7,
                            EstaActivo = false,
                            NombreArea = "Montaje"
                        },
                        new
                        {
                            Id = 8,
                            EstaActivo = false,
                            NombreArea = "Mantenimiento"
                        },
                        new
                        {
                            Id = 9,
                            EstaActivo = false,
                            NombreArea = "Administración"
                        },
                        new
                        {
                            Id = 10,
                            EstaActivo = false,
                            NombreArea = "Compras"
                        });
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.AreaDetalleOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("Tiempo")
                        .HasColumnType("int");

                    b.Property<int>("TiempoEstimadoMinutos")
                        .HasColumnType("int");

                    b.Property<int>("TiempoPausadoAcumuladoMinutos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("OrdenId");

                    b.ToTable("AreaDetalleOrdenes");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Entregado")
                        .HasMaxLength(30)
                        .HasColumnType("bit");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("MedioDePagoId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedioDePagoId");

                    b.HasIndex("OrdenId");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Estante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.ToTable("Estantes");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.EventoNotificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("ReferenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EventosNotificados");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantDisponible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<int?>("EstanteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaBorrado")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnidadMedidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstanteId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.InsumoDetalleOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CantidadDescontada")
                        .HasColumnType("int");

                    b.Property<int>("CantidadPendiente")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("Insuficiente")
                        .HasColumnType("bit");

                    b.Property<int?>("InsumoId")
                        .HasColumnType("int");

                    b.Property<int?>("OrdenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("OrdenId");

                    b.ToTable("InsumoDetalleOrdenes");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.MedioDePago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre_Medio")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nombre_Medio" }, "Nombre_Medio_UQ")
                        .IsUnique()
                        .HasFilter("[Nombre_Medio] IS NOT NULL");

                    b.ToTable("MedioDePagos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre_Medio = "Efectivo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre_Medio = "Tarjeta de crédito"
                        },
                        new
                        {
                            Id = 3,
                            Nombre_Medio = "Transferencia bancaria"
                        },
                        new
                        {
                            Id = 4,
                            Nombre_Medio = "Cheque"
                        },
                        new
                        {
                            Id = 5,
                            Nombre_Medio = "Mercado Pago"
                        },
                        new
                        {
                            Id = 6,
                            Nombre_Medio = "PayPal"
                        });
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsLeida")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Mensaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaPactada")
                        .HasColumnType("date");

                    b.Property<string>("NombreOrden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NroOT")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex(new[] { "NroOT" }, "NroOT_UQ")
                        .IsUnique();

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int>("NroPedido")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProveedor");

                    b.HasIndex(new[] { "NroPedido" }, "NroPedido_UQ")
                        .IsUnique();

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.PedidoDetalleInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool>("EntregaParcial")
                        .HasColumnType("bit");

                    b.Property<bool>("EntregaTotal")
                        .HasColumnType("bit");

                    b.Property<bool>("EsSolicitado")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("FechaUso")
                        .HasColumnType("date");

                    b.Property<int?>("IdInsumo")
                        .HasColumnType("int");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("int");

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdInsumo");

                    b.HasIndex("IdPedido");

                    b.ToTable("PedidoDetalleInsumos");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Plano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<string>("RutaOriginal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaSVG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "JuanPérez322@gmail.com",
                            Nombre = "Acme S.A.",
                            Telefono = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            Correo = "MaríaGómez323@gmail.com",
                            Nombre = "Industrias Globales",
                            Telefono = "987654321"
                        },
                        new
                        {
                            Id = 3,
                            Correo = "CarlosRodríguez243@gmail.com",
                            Nombre = "Suministros Técnicos",
                            Telefono = "456123789"
                        },
                        new
                        {
                            Id = 4,
                            Correo = "AnaFernández423@gmail.com",
                            Nombre = "Materiales y Más",
                            Telefono = "789456123"
                        },
                        new
                        {
                            Id = 5,
                            Correo = "LuisMartínez902@gmail.com",
                            Nombre = "Soluciones Industriales",
                            Telefono = "321654987"
                        },
                        new
                        {
                            Id = 6,
                            Correo = "SofíaLópez434@gmail.com",
                            Nombre = "Equipos y Herramientas S.R.L.",
                            Telefono = "654987321"
                        });
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.UnidadConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FactorConversion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnidadDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadOrigenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadDestinoId");

                    b.HasIndex("UnidadOrigenId");

                    b.ToTable("UnidadConversiones");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsBase")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LongitudPorUnidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnidadesPorAgrupacion")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadesPorCaja")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UnidadMedidas");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.AreaDetalleOrden", b =>
                {
                    b.HasOne("Armeccor.Datos.Entidades.Area", "Area")
                        .WithMany("AreaOrdenes")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Armeccor.Datos.Entidades.Orden", "Orden")
                        .WithMany("AreaDetalleOrdenes")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Entrega", b =>
                {
                    b.HasOne("Armeccor.Datos.Entidades.MedioDePago", "Medio_De_Pago")
                        .WithMany("Entregas")
                        .HasForeignKey("MedioDePagoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Armeccor.Datos.Entidades.Orden", "Orden")
                        .WithMany("Entregas")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Medio_De_Pago");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Insumo", b =>
                {
                    b.HasOne("Armeccor.Datos.Entidades.Estante", "Estante")
                        .WithMany("Insumos")
                        .HasForeignKey("EstanteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Armeccor.Datos.Entidades.UnidadMedida", "UnidadBase")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estante");

                    b.Navigation("UnidadBase");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.InsumoDetalleOrden", b =>
                {
                    b.HasOne("Armeccor.Datos.Entidades.Insumo", "Insumo")
                        .WithMany("InsumoOrdenes")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Armeccor.Datos.Entidades.Orden", "Orden")
                        .WithMany("InsumoOrdenes")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Insumo");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Orden", b =>
                {
                    b.HasOne("Armeccor.Datos.Entidades.Cliente", "Cliente")
                        .WithMany("Ordenes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Pedido", b =>
                {
                    b.HasOne("Armeccor.Datos.Entidades.Proveedor", "Proveedor")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.PedidoDetalleInsumo", b =>
                {
                    b.HasOne("Armeccor.Datos.Entidades.Insumo", "Insumo")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdInsumo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Armeccor.Datos.Entidades.Pedido", "Pedido")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Insumo");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Plano", b =>
                {
                    b.HasOne("Armeccor.Datos.Entidades.Orden", "Orden")
                        .WithMany("Planos")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.UnidadConversion", b =>
                {
                    b.HasOne("Armeccor.Datos.Entidades.UnidadMedida", "UnidadDestino")
                        .WithMany()
                        .HasForeignKey("UnidadDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armeccor.Datos.Entidades.UnidadMedida", "UnidadOrigen")
                        .WithMany()
                        .HasForeignKey("UnidadOrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadDestino");

                    b.Navigation("UnidadOrigen");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Area", b =>
                {
                    b.Navigation("AreaOrdenes");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Cliente", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Estante", b =>
                {
                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Insumo", b =>
                {
                    b.Navigation("DetallePedidos");

                    b.Navigation("InsumoOrdenes");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.MedioDePago", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Orden", b =>
                {
                    b.Navigation("AreaDetalleOrdenes");

                    b.Navigation("Entregas");

                    b.Navigation("InsumoOrdenes");

                    b.Navigation("Planos");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Pedido", b =>
                {
                    b.Navigation("DetallePedidos");
                });

            modelBuilder.Entity("Armeccor.Datos.Entidades.Proveedor", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
